default_configs = {
    'music': {
        'aggregator': 'sum',
        'n_epochs': 100,
        'neighbor_sample_size': 8,
        'dim': 256,
        'n_iter': 1,
        'batch_size': 256,
        'l2_weight': 5e-4,
        'lr': 5e-4,
        'ratio': 1,
        'contrastive_learning': True,
        'contrastive_weight': 0.001,
    },
    'book': {
        'aggregator': 'sum',
        'n_epochs': 100,
        'neighbor_sample_size': 4,
        'dim': 64,
        'n_iter': 1,
        'batch_size': 256,
        'l2_weight': 2e-4,
        'lr': 2e-4,
        'ratio': 1,
        'contrastive_learning': True,
        'contrastive_weight': 0.1,
    },
    'movie1M': {
        'aggregator': 'sum',
        'n_epochs': 200,
        'neighbor_sample_size': 4,
        'dim': 64,
        'n_iter': 1,
        'batch_size': 2048,
        'l2_weight': 6e-5,
        'lr': 1e-3,
        'ratio': 1,
        'contrastive_learning': True,
        'contrastive_weight': 0.001,
    }
}